/**
 * Mindlock Score Registry — TypeScript Client
 *
 * Thin wrapper around the deployed score_registry Anchor program.
 * Called from KnowledgeGate.tsx after every successful quiz pass.
 *
 * Program: A2n66MaKH2KhcJJnnBfh56VrmATAA8kPt7iXq5QEQTAx (devnet)
 * IDL: target/idl/score_registry.json (generated by anchor build)
 */

import { Connection, PublicKey, Transaction, SystemProgram } from '@solana/web3.js';
import { NETWORK_CONFIG } from '../config/network';
import { LEADERBOARD_PROGRAM_ID } from './leaderboardClient';

// ============================================================================
// PDA Seeds — must match program exactly
// ============================================================================
const USER_SCORE_SEED = 'user_score';
const GLOBAL_STATS_SEED = 'global_stats';

// ============================================================================
// Instruction discriminators (Anchor sha256("global:<ix_name>")[0..8])
// These are pre-computed from the deployed IDL.
// ============================================================================
const DISCRIMINATORS = {
    initUserScore:  Buffer.from([0x61, 0xe5, 0x9a, 0x1d, 0x2a, 0x71, 0x40, 0xb2]),
    submitScore:    Buffer.from([0x53, 0x34, 0xa1, 0x78, 0x9e, 0xc2, 0x4f, 0xd0]),
    initGlobalStats:Buffer.from([0x5f, 0x1a, 0xb3, 0x2c, 0x8e, 0x47, 0xd1, 0x90]),
};

// ============================================================================
// PDA helpers
// ============================================================================
export function getUserScorePDA(wallet: PublicKey): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
        [Buffer.from(USER_SCORE_SEED), wallet.toBuffer()],
        LEADERBOARD_PROGRAM_ID
    );
}

export function getGlobalStatsPDA(): [PublicKey, number] {
    return PublicKey.findProgramAddressSync(
        [Buffer.from(GLOBAL_STATS_SEED)],
        LEADERBOARD_PROGRAM_ID
    );
}

// ============================================================================
// submitScore — called after every successful quiz pass
//
// Parameters:
//   wallet          — user's PublicKey
//   signTransaction — MWA signer from createMWASigner()
//   focusMinutes    — minutes of focus earned (grace period / quiz time)
//   accuracy        — 0-100, percent correct this session
//   questions       — the quiz question array (for content hash)
//   maxDifficulty   — 0=Easy, 1=Medium, 2=Hard (max difficulty answered)
// ============================================================================
export async function submitScoreOnChain(params: {
    wallet: PublicKey;
    signTransaction: (tx: Transaction) => Promise<Transaction>;
    focusMinutes: number;
    accuracy: number;
    questions: Array<{ difficulty?: string }>;
    maxDifficulty?: number;
    /** Pre-computed SHA-256 hash (from computeQuestionSetHashBytes). Falls back to legacy XOR if not provided. */
    questionSetHash?: Uint8Array;
}): Promise<{ success: boolean; txSignature?: string; error?: string }> {
    const { wallet, signTransaction, focusMinutes, accuracy, questions, maxDifficulty = 2, questionSetHash } = params;

    try {
        const connection = new Connection(NETWORK_CONFIG.rpcUrl, 'confirmed');
        const [userScorePDA] = getUserScorePDA(wallet);
        const [globalStatsPDA] = getGlobalStatsPDA();

        // Use pre-computed SHA-256 hash if available, otherwise fall back to legacy XOR
        const hashBytes = questionSetHash ?? computeQuestionHashLegacy(questions);

        // Check if UserScore account exists — if not, we include init instruction
        const userScoreAccount = await connection.getAccountInfo(userScorePDA);
        const needsInit = !userScoreAccount;

        const instructions = [];

        // If first time — include init_user_score
        if (needsInit) {
            const initData = Buffer.alloc(8);
            DISCRIMINATORS.initUserScore.copy(initData, 0);
            instructions.push({
                programId: LEADERBOARD_PROGRAM_ID,
                keys: [
                    { pubkey: wallet,          isSigner: true,  isWritable: true  },
                    { pubkey: userScorePDA,    isSigner: false, isWritable: true  },
                    { pubkey: globalStatsPDA,  isSigner: false, isWritable: true  },
                    { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
                ],
                data: initData,
            });
        }

        // submit_score instruction
        // Layout: discriminator(8) + focus_minutes(4) + accuracy(4) + question_set_hash(32) + max_difficulty(1) = 49
        const submitData = Buffer.alloc(49);
        DISCRIMINATORS.submitScore.copy(submitData, 0);
        submitData.writeUInt32LE(focusMinutes, 8);
        submitData.writeUInt32LE(accuracy, 12);
        Buffer.from(hashBytes).copy(submitData, 16);
        submitData.writeUInt8(maxDifficulty, 48);

        instructions.push({
            programId: LEADERBOARD_PROGRAM_ID,
            keys: [
                { pubkey: wallet,         isSigner: true,  isWritable: true },
                { pubkey: userScorePDA,   isSigner: false, isWritable: true },
                { pubkey: globalStatsPDA, isSigner: false, isWritable: true },
            ],
            data: submitData,
        });

        // Build transaction
        const { blockhash } = await connection.getLatestBlockhash('confirmed');
        const tx = new Transaction({
            recentBlockhash: blockhash,
            feePayer: wallet,
        });
        instructions.forEach(ix => tx.add(ix));

        // Sign via MWA (Seed Vault biometric)
        const signedTx = await signTransaction(tx);

        // Send
        const rawTx = signedTx.serialize();
        const txSignature = await connection.sendRawTransaction(rawTx, {
            skipPreflight: false,
            preflightCommitment: 'confirmed',
        });

        await connection.confirmTransaction(txSignature, 'confirmed');

        __DEV__ && console.log(`✅ QuizPassed on-chain: ${txSignature}`);
        return { success: true, txSignature };

    } catch (error) {
        // Non-fatal — don't block the user's unlock if the attestation fails
        console.warn('submitScoreOnChain failed (non-fatal):', error);
        return { success: false, error: (error as Error).message };
    }
}

// ============================================================================
// Legacy content hash — deterministic XOR (fallback if SHA-256 not provided)
// Returns [u8; 32] compatible with the program's question_set_hash field.
// Kept for backward compatibility; prefer computeQuestionSetHashBytes() from
// dynamicQuestions.ts for the real SHA-256 implementation.
// ============================================================================
function computeQuestionHashLegacy(questions: Array<{ difficulty?: string }>): Uint8Array {
    const combined = JSON.stringify(questions);
    const hash = new Uint8Array(32);
    for (let i = 0; i < combined.length; i++) {
        hash[i % 32] ^= combined.charCodeAt(i) ^ (i & 0xff);
    }
    return hash;
}
